# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AutoTestGo < Formula
  desc ""
  homepage "https://github.com/angshumanHalder/auto-test-go"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/angshumanHalder/auto-test-go/releases/download/v0.0.3/auto-test-go_0.0.3_Darwin_arm64.tar.gz"
      sha256 "0fe0da7e491afa0964ca862cf41b21e8d25b222de06bc560b0e294917481eb60"

      def install
        bin.install "auto-test-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/angshumanHalder/auto-test-go/releases/download/v0.0.3/auto-test-go_0.0.3_Linux_arm64.tar.gz"
      sha256 "c2e8b49d50a38aad19b17b84dea9486e485644b3af812544bd1c7036df54f457"

      def install
        bin.install "auto-test-go"
      end
    end
  end
end
